on:
  push:
    branches: [main]

jobs:
  tests:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: action/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with: 
          go-version: "1.23.0"

      - name: Build App
        run: ./scripts/buildprod.sh
